name: Deploy to Vercel

on:
  push:
    branches: [main]  # main 브랜치 푸시 시 프로덕션 배포
  pull_request:
    branches: [main]  # PR 시 Preview 배포

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # 코드 체크아웃

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # 프로젝트에 맞게 변경

      - name: Install dependencies
        run: npm ci  # 또는 yarn install

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25  # Vercel 액션 사용 (Marketplace에서 설치됨)<grok-card data-id="7475e2" data-type="citation_card"></grok-card>
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}  # Secrets에서 불러옴
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}  # Vercel Org ID (필요 시 Secrets 추가)
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}  # Vercel Project ID (필요 시 Secrets 추가)
          vercel-args: ${{ github.ref == 'refs/heads/main' && '--prod' || '' }}  # main 브랜치만 프로덕션 배포 (PR은 Preview)